version: "3"

services:
  nuxt:
    build: ./app/
    container_name: serpay
    restart: always
    ports:
      - "3000:3000"
    command:
      "yarn run start"

  nginx:
    image: nginx:1.15
    container_name: serpay-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - nuxt